modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="tech_revised"
version="${file.jarVersion}"
displayName="Tech Revised"
authors="stefa"
description='''
Tech Revised core content focused on the Electric Arc Furnace.
'''

[[dependencies.tech_revised]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.tech_revised]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.tech_revised]]
modId="jei"
mandatory=false
versionRange="[15.20.0,)"
ordering="AFTER"
side="CLIENT"
